### ISSUE TITLE
Warning: Unknown prop `delay` on <div> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by mar-muel** [fakiolinho/react-loading#32]
Hi everything works great, thanks! But I get the following warning:

> Warning: Unknown prop `delay` on <div> tag. Remove this prop from the element.

I'm using Chrome Version 61.0.3163.100 (Official Build) (64-bit)

I get the same warning on the example page https://www.webpackbin.com/bins/-KmrzFstbIElhoFgQX96

**Comment by fakiolinho** [comment]
Hmm, yeah you 're right, I saw the issue. Thanks @mar-muel

**Comment by fakiolinho** [comment]
Fixed in #33 release v1.0.1

**Comment by aranchafoz** [comment]
Sorry for reopen, but I still have the same warning on version 2.0.1, are you sure this is really fixed?

![captura de pantalla 2018-04-20 a las 9 45 43](https://user-images.githubusercontent.com/14368971/39037046-aa98733c-447f-11e8-8404-a1fce460d87b.png)
My code:
![captura de pantalla 2018-04-20 a las 9 47 47](https://user-images.githubusercontent.com/14368971/39037157-f4c6837c-447f-11e8-880f-7e44c56ec15b.png)

**Comment by fakiolinho** [comment]
Hmm no you are right it is definitely valid this bug
